name: azurite functional tests
permissions: {}
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
              
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
        id: go

      - name: Set up Docker Compose
        run: |
          docker compose -f tests/docker-compose.yml --env-file .env.dev --project-directory . up -d azurite azuritegw

      - name: Wait for Azurite to be ready
        run: sleep 40

      - name: Get Dependencies
        run: |
          go mod download
  
      - name: Build and Run
        run: |
          make
          ./versitygw test -a user -s pass -e http://127.0.0.1:7070 full-flow --azure
  
      - name: Shut down services
        run: |
          docker compose -f tests/docker-compose.yml --env-file .env.dev --project-directory . down azurite azuritegw
