name: functional tests
permissions: {}
on: pull_request

jobs:
  build:
    name: RunTests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
      id: go

    - name: Get Dependencies
      run: |
        go mod download

    - name: Build and Run
      run: |
        make testbin
        ./runtests.sh

    - name: Coverage Report
      run: |
        go tool covdata percent -i=/tmp/covdata
