name: staticcheck
permissions: {}
on: pull_request
jobs: 

  build: 
    name: Check
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
      id: go
 
    - name: "staticcheck"
      uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"
